Данный файл предназначен для подготовки датасета из основных parqeut файлов

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_stats = pd.read_parquet("player_starts_train.parquet")

In [3]:
df_stats.head()

,date,user_id,item_id,watch_time,is_autorized
0,2023-07-21 19:04:50+03:00,user_12964323,video_1042531,51,0
1,2023-07-21 02:02:41+03:00,user_16517,video_1707159,31,0
2,2023-07-21 22:00:47+03:00,user_15057892,video_1989987,9,0
3,2023-07-21 19:09:43+03:00,user_2846972,video_1356486,-1,0
4,2023-07-21 11:06:58+03:00,user_20517034,video_1380654,11,0

In [13]:
df_stats['user_id'].nunique()

28800762

In [5]:
df_sample = pd.read_csv('sample_submission.csv')
sample_users = set(list(df_sample['user_id'].unique()))

In [ ]:
#sample_users

In [6]:
df_stats_for_sample = df_stats[df_stats['user_id'].isin(sample_users)]

In [12]:
df_stats_for_sample['user_id'].nunique()

57822

In [14]:
df_emotions = pd.read_csv("emotions.csv")

In [4]:
# Фильтр реакций по 21.08.2023
#df_emotions = df_emotions[(df_emotions['date'] >= '2023-08-21') & (df_emotions['date'] < '2023-08-22')]

In [15]:
df_emotions[df_emotions.duplicated(subset=['user_id', 'item_id'],keep=False)].sort_values(by=['user_id','item_id'])

,date,user_id,item_id,type,emoji
58313,2023-08-05 12:40:04+03:00,user_10000745,video_1850207,v_top,v_top
273659,2023-08-05 12:36:36+03:00,user_10000745,video_1850207,pos_emotions,Heart
187138,2023-08-03 09:34:27+03:00,user_10002332,video_1218945,pos_emotions,New_Fire
244097,2023-08-03 09:34:23+03:00,user_10002332,video_1218945,v_top,v_top
117410,2023-07-27 11:41:27+03:00,user_10002332,video_1540173,v_top,v_top
...,...,...,...,...,...
167077,2023-08-07 12:16:06+03:00,user_9996320,video_64845,v_top,v_top
120984,2023-08-10 15:53:38+03:00,user_9996400,video_1176672,v_top,v_top
296285,2023-08-10 15:52:39+03:00,user_9996400,video_1176672,pos_emotions,Like
212216,2023-07-26 10:26:58+03:00,user_9997104,video_1425966,v_top,v_top
248208,2023-07-26 10:51:54+03:00,user_9997104,video_1425966,pos_emotions,Like

In [6]:
#pd.merge(df_stats, df_emotions,how='left', )

In [16]:
df_new_emo = df_emotions.copy(deep=True)

In [17]:
df_new_emo['type'].unique()

array(['v_top', 'pos_emotions', 'neg_emotions'], dtype=object)

In [18]:
df_new_emo

,date,user_id,item_id,type,emoji
0,2023-08-03 21:37:22+03:00,user_21883648,video_2247834,v_top,v_top
1,2023-08-03 21:04:54+03:00,user_24016046,video_2247834,v_top,v_top
2,2023-08-03 20:37:06+03:00,user_20748867,video_22669,v_top,v_top
3,2023-08-03 20:44:12+03:00,user_21545120,video_645471,v_top,v_top
4,2023-08-03 20:45:17+03:00,user_28987830,video_2346806,v_top,v_top
...,...,...,...,...,...
369424,2023-08-02 11:43:43+03:00,user_21597217,video_1180057,pos_emotions,Like
369425,2023-07-25 16:26:35+03:00,user_6805283,video_1180057,pos_emotions,Like
369426,2023-07-28 13:07:10+03:00,user_5419928,video_1180057,pos_emotions,Like
369427,2023-08-07 18:16:30+03:00,user_12044809,video_1180057,pos_emotions,Like
369428,2023-07-23 20:52:56+03:00,user_29042253,video_1180057,neg_emotions,Dislike

In [19]:
df_new_emo['is_v_top'] = np.where(df_new_emo['type'] == 'v_top', 1, 0)
df_new_emo['pos_emo'] = np.where(df_new_emo['type'] == 'pos_emotions', df_new_emo['emoji'], '')
df_new_emo['neg_emo'] = np.where(df_new_emo['type'] == 'neg_emotions', df_new_emo['emoji'], '')

In [20]:
df_new_emo[df_new_emo.duplicated(subset=['user_id','item_id'],keep=False)].sort_values(by=['user_id','item_id'])

,date,user_id,item_id,type,emoji,is_v_top,pos_emo,neg_emo
58313,2023-08-05 12:40:04+03:00,user_10000745,video_1850207,v_top,v_top,1,,
273659,2023-08-05 12:36:36+03:00,user_10000745,video_1850207,pos_emotions,Heart,0,Heart,
187138,2023-08-03 09:34:27+03:00,user_10002332,video_1218945,pos_emotions,New_Fire,0,New_Fire,
244097,2023-08-03 09:34:23+03:00,user_10002332,video_1218945,v_top,v_top,1,,
117410,2023-07-27 11:41:27+03:00,user_10002332,video_1540173,v_top,v_top,1,,
...,...,...,...,...,...,...,...,...
167077,2023-08-07 12:16:06+03:00,user_9996320,video_64845,v_top,v_top,1,,
120984,2023-08-10 15:53:38+03:00,user_9996400,video_1176672,v_top,v_top,1,,
296285,2023-08-10 15:52:39+03:00,user_9996400,video_1176672,pos_emotions,Like,0,Like,
212216,2023-07-26 10:26:58+03:00,user_9997104,video_1425966,v_top,v_top,1,,
248208,2023-07-26 10:51:54+03:00,user_9997104,video_1425966,pos_emotions,Like,0,Like,

In [21]:
df_new_emo.agg({'pos_emo': 'sum', 'is_v_top':'sum', 'neg_emo': 'sum'})

pos_emo     LikeNew_FireNew_FireLikeLikeLikeLikeLikeLikeLi...
is_v_top                                               199907
neg_emo     DislikeDislikeDislikeDislikeDislikeDislikeDisl...
dtype: object

In [22]:
df_new_emo = df_new_emo.groupby(by=['user_id', 'item_id']).agg({'date': 'min','pos_emo': 'sum', 'is_v_top':'sum', 'neg_emo': 'sum'}).reset_index()

In [27]:
df_stats_day = df_stats[(df_stats['date'] >= '2023-08-21') & (df_stats['date'] < '2023-08-22')]

In [25]:
df_stats_day = pd.concat([df_stats_day, df_stats_for_sample]).reset_index(drop=True)

In [28]:
df_stats_grouped = df_stats_day.groupby(by=['user_id','item_id']).agg({'date': 'min', 'watch_time': 'sum', 'is_autorized':'sum'})

In [29]:
df_stats_grouped = df_stats_grouped.reset_index()

In [30]:
df_stats_grouped = df_stats_grouped[df_stats_grouped['is_autorized'] < 15]

In [31]:
df_stats_grouped.loc[df_stats_grouped.is_autorized > 0, 'is_autorized'] = 1

In [32]:
df2 = pd.merge(left=df_stats_grouped,right=df_new_emo,how='left',on=['user_id','item_id'])

In [33]:
df2 = df2.rename(columns={'date_x': 'date_watch', 'date_y': 'date_reaction'})

In [34]:
df_meta_video = pd.read_parquet('videos.parquet')

In [35]:
df2 = pd.merge(left=df2,right=df_meta_video, how='left', on='item_id')

In [36]:
df2['duration'] = df2['duration']/1000
df2['ctr.CTR_10days_21_07'] = df2['ctr.CTR_10days_21_07'].fillna(0)
df2['ctr.CTR_10days_01_08'] = df2['ctr.CTR_10days_01_08'].fillna(0)
df2['ctr.CTR_10days_10_08'] = df2['ctr.CTR_10days_10_08'].fillna(0)
df2['ctr.CTR_10days_21_08'] = df2['ctr.CTR_10days_21_08'].fillna(0)

In [129]:
#df2.head()

,user_id,item_id,date_watch,watch_time,is_autorized,date_reaction,pos_emo,is_v_top,neg_emo,video_title,...,video_description,category_title,publicated,duration,channel_sub,tv_sub,ctr.CTR_10days_21_07,ctr.CTR_10days_01_08,ctr.CTR_10days_10_08,ctr.CTR_10days_21_08
0,user_10000000,video_1487101,2023-08-21 20:25:47+03:00,2310,0,NaN,NaN,NaN,NaN,"Звезды в Африке, 3 сезон, 13 выпуск",...,Премьера! В третьем сезоне экстремально-приклю...,Телепередачи,2022-12-05 11:00:20+03:00,5377.480,75496,0,0.294598,0.260142,0.237338,0.252909
1,user_10000000,video_222807,2023-08-21 19:06:33+03:00,4611,0,NaN,NaN,NaN,NaN,Четыре свадьбы: Свадьбы в Турции,...,«Четыре свадьбы» отправляются в Турцию! Невест...,Телепередачи,2023-08-10 21:19:06+03:00,6919.000,16723,0,0.000000,0.000000,0.025105,0.039709
2,user_10000033,video_1761620,2023-08-21 07:02:56+03:00,196,0,NaN,NaN,NaN,NaN,Соловьёв LIVE | Круглосуточный канал,...,В прямом эфире Соловьёв LIVE – новости и размы...,Телепередачи,2022-10-14 12:06:53+03:00,0.000,343030,0,0.000000,0.000000,0.000000,0.000000
3,user_10000087,video_1106848,2023-08-21 03:55:46+03:00,490,0,NaN,NaN,NaN,NaN,КОЛЛЕКТИВ 2.0 ЗАПУЩЕН | Atomic Heart: Инстинкт...,...,"ЙОУ БЕЗРАБОТНЫЕ, это полное прохождение НОВОГО...",Видеоигры,2023-08-17 13:57:07+03:00,1059.917,19764,0,0.000000,0.000000,0.000000,0.010326
4,user_10000087,video_633280,2023-08-21 04:04:26+03:00,1,0,NaN,NaN,NaN,NaN,Atomic Heart - «Инстинкт Истребления» Прохожд...,...,Atomic Heart - «Инстинкт Истребления» Прохожд...,Видеоигры,2023-08-14 10:00:20+03:00,3286.529,59,0,0.000000,0.000000,0.000000,0.011585

In [37]:
df_live = df2[df2['duration'] == 0]

In [38]:
df_live = df_live.groupby('item_id').agg({'watch_time': 'max'}).reset_index()

In [39]:
df_live = df_live.rename(columns={'watch_time': 'live_duration'})

In [40]:
df2 = pd.merge(left=df2, right=df_live, on='item_id', how='left')

In [41]:
df2['duration'] = np.where(~df2['live_duration'].isna(), df2['live_duration'], df2['duration'])

In [42]:
df2 = df2.drop(columns=['live_duration'])

In [41]:
df2.to_csv('final_user_video_reaction_meta.csv')

In [42]:
df2

,user_id,item_id,date_watch,watch_time,is_autorized,date_reaction,pos_emo,is_v_top,neg_emo,video_title,...,video_description,category_title,publicated,duration,channel_sub,tv_sub,ctr.CTR_10days_21_07,ctr.CTR_10days_01_08,ctr.CTR_10days_10_08,ctr.CTR_10days_21_08
0,user_10000010,video_1066637,2023-08-20 10:41:30+03:00,332,0,NaN,NaN,NaN,NaN,Школа Шишкиного Леса. Математика. Циркуль. Окр...,...,None,Детям,2023-02-27 14:00:15+03:00,384.000,219,0,0.000000,0.000000,0.000000,0.000000
1,user_10000029,video_1896756,2023-08-20 07:59:22+03:00,102,0,NaN,NaN,NaN,NaN,Тяга и зависимость от сладкого. Как их поборот...,...,Простые и доступные способы снизить тягу к сла...,Здоровье,2023-08-01 16:36:23+03:00,189.706,7722,0,0.000000,1.000000,0.000117,0.012992
2,user_10000050,video_257266,2023-08-20 19:46:15+03:00,52,0,NaN,NaN,NaN,NaN,Как избавиться от мышей За 3 Секунды...!!!...,...,Как избавиться от мышей За 3 Секунды...!!!...,Лайфхаки,2023-03-22 09:49:50+03:00,61.900,748,0,0.117647,0.123762,0.151079,0.180807
3,user_10000060,video_1425649,2023-08-20 22:21:25+03:00,2,0,NaN,NaN,NaN,NaN,"Зимородок (2022) 1,2,3,4,5,6,7,8,9,10,11,12,13...",...,Сериал «Зимородок» вышел в 2022 году и на данн...,Сериалы,2022-09-28 12:38:07+03:00,88.522,6372,0,0.124084,0.121994,0.105913,0.095314
4,user_1000009,video_25806,2023-08-20 22:12:39+03:00,69,0,NaN,NaN,NaN,NaN,Ледовый дрифт на BMW e39,...,"Голый лёд, плохая резина, трещина в подрамнике...",Авто-мото,2023-01-29 03:01:34+03:00,193.467,9049,0,0.000000,0.000000,0.000000,0.020833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1950448,user_9999880,video_1306097,2023-08-20 21:32:29+03:00,-1,0,NaN,NaN,NaN,NaN,Best Sexy Moments in Women’s Sports,...,None,Лайфстайл,2023-06-08 08:25:29+03:00,131.379,27,0,0.000000,0.000000,0.000000,0.000000
1950449,user_9999880,video_1340496,2023-08-20 21:13:52+03:00,465,0,NaN,NaN,NaN,NaN,Нелепые моменты в спорте,...,Нелепые моменты в спорте,Развлечения,2022-12-02 10:37:29+03:00,546.300,53,0,0.000000,0.000000,0.000000,0.000000
1950450,user_9999880,video_1641420,2023-08-20 21:31:59+03:00,21,0,NaN,NaN,NaN,NaN,Young gymnastics with Lucy,...,#рутуб #rutube #йога #yoga #yogastretching #yo...,Спорт,2023-08-20 02:14:01+03:00,67.902,6,0,0.000000,0.000000,0.000000,0.100000
1950451,user_9999925,video_1552291,2023-08-20 07:09:52+03:00,2,0,NaN,NaN,NaN,NaN,Прямой эфир МИР,...,"Тем, кто интересуется жизнью, историй, культур...",Телепередачи,2019-06-28 13:57:29+03:00,2500.000,4773,0,0.051948,0.000000,0.000000,0.000000
1950452,user_999993,video_1843964,2023-08-20 17:34:55+03:00,171,0,NaN,NaN,NaN,NaN,Ислам Итляшев - Кобра _ Премьера клипа 2022,...,Ислам Итляшев - Кобра _ Премьера клипа 2022,Аудио,2022-04-18 20:46:03+03:00,173.128,16,0,0.000000,0.000000,0.000000,0.000000

In [109]:
users_20_aug = set(list(df2[df2['category_title'] == 'Детям']['user_id'].unique()))

In [65]:
len(sample_users.intersection(users_20_aug))

23841

In [66]:
df_21_aug = pd.read_csv('user_video_reaction_meta.csv')

C:\Users\bulae\AppData\Local\Temp\ipykernel_17740\3119158115.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_21_aug = pd.read_csv('user_video_reaction_meta.csv')

In [67]:
users_21_aug = set(list(df_21_aug['user_id'].unique()))

In [110]:
sample_users.intersection(users_20_aug).intersection(users_21_aug)

{'user_10046996',
 'user_10054797',
 'user_10103364',
 'user_10121572',
 'user_10211566',
 'user_10324305',
 'user_10335291',
 'user_10414150',
 'user_10563449',
 'user_10568139',
 'user_10589824',
 'user_10629634',
 'user_10633150',
 'user_10661187',
 'user_10691764',
 'user_10693344',
 'user_10711400',
 'user_10719865',
 'user_10773095',
 'user_10855702',
 'user_10861263',
 'user_10905320',
 'user_10926696',
 'user_10933748',
 'user_10979652',
 'user_11050053',
 'user_11075896',
 'user_11114235',
 'user_11145578',
 'user_11147230',
 'user_11169552',
 'user_1117757',
 'user_11179829',
 'user_11183740',
 'user_11259553',
 'user_11302797',
 'user_11355644',
 'user_11405066',
 'user_1140983',
 'user_11491141',
 'user_11669814',
 'user_11703373',
 'user_11718398',
 'user_11764072',
 'user_11856536',
 'user_11860370',
 'user_11886309',
 'user_12027793',
 'user_12059557',
 'user_12067737',
 'user_12091581',
 'user_12097391',
 'user_12229595',
 'user_12252617',
 'user_1230872',
 'user_12327277',
 'user_12365',
 'user_12403764',
 'user_12406403',
 'user_12431512',
 'user_12446565',
 'user_12503824',
 'user_12512564',
 'user_12536208',
 'user_12570062',
 'user_12606804',
 'user_12613456',
 'user_12621967',
 'user_12751799',
 'user_1275377',
 'user_12899167',
 'user_12915641',
 'user_12929409',
 'user_12953277',
 'user_13030487',
 'user_13060110',
 'user_13062246',
 'user_13104358',
 'user_13135040',
 'user_13172711',
 'user_13184653',
 'user_13253112',
 'user_13263927',
 'user_13267788',
 'user_13321367',
 'user_13376039',
 'user_13424833',
 'user_13433814',
 'user_13460281',
 'user_13556275',
 'user_13576062',
 'user_13593802',
 'user_13597102',
 'user_13610216',
 'user_13619349',
 'user_13619371',
 'user_13764372',
 'user_13765588',
 'user_13795016',
 'user_13883308',
 'user_13920203',
 'user_14048893',
 'user_14086203',
 'user_14097589',
 'user_14251160',
 'user_1428999',
 'user_14379907',
 'user_14395428',
 'user_1439771',
 'user_14413025',
 'user_14459263',
 'user_14463802',
 'user_14549100',
 'user_14553284',
 'user_14553813',
 'user_14595712',
 'user_1461513',
 'user_14680429',
 'user_14701337',
 'user_14713046',
 'user_1471763',
 'user_14727028',
 'user_14729483',
 'user_14759140',
 'user_14829508',
 'user_14838711',
 'user_14844264',
 'user_14858986',
 'user_14877138',
 'user_14895491',
 'user_14910039',
 'user_15002295',
 'user_15071724',
 'user_15073845',
 'user_15132940',
 'user_1516348',
 'user_15180819',
 'user_15200953',
 'user_15222598',
 'user_1525978',
 'user_15281216',
 'user_15296811',
 'user_15381658',
 'user_15403341',
 'user_15456104',
 'user_15466314',
 'user_15478739',
 'user_15496719',
 'user_15586987',
 'user_15587066',
 'user_15650919',
 'user_15750725',
 'user_15790034',
 'user_15802552',
 'user_15965429',
 'user_16021157',
 'user_16090612',
 'user_16188118',
 'user_16217320',
 'user_16233330',
 'user_1632353',
 'user_16334146',
 'user_16334300',
 'user_16355623',
 'user_1636658',
 'user_16374708',
 'user_16394725',
 'user_16398907',
 'user_16416705',
 'user_16459075',
 'user_16495144',
 'user_16552117',
 'user_16581418',
 'user_16590241',
 'user_16626794',
 'user_16636181',
 'user_166440',
 'user_16657631',
 'user_16703088',
 'user_16716088',
 'user_16735695',
 'user_16871880',
 'user_16874352',
 'user_16906644',
 'user_16923183',
 'user_16941759',
 'user_16953291',
 'user_16978364',
 'user_17047148',
 'user_17080725',
 'user_17114569',
 'user_17202421',
 'user_17449539',
 'user_17465635',
 'user_17524578',
 'user_17569565',
 'user_17575866',
 'user_17594437',
 'user_17640096',
 'user_17683197',
 'user_17684489',
 'user_17797242',
 'user_17804332',
 'user_17854451',
 'user_17857455',
 'user_17870181',
 'user_17880322',
 'user_17889752',
 'user_17923676',
 'user_17967396',
 'user_17989361',
 'user_18005853',
 'user_1810291',
 'user_18112',
 'user_18135141',
 'user_18156207',
 'user_18200745',
 'user_18284820',
 'user_18325722',
 'user_18327547',
 'user_18348687',
 'user_18416695',
 'user_18546911',
 'user_18624497',
 'user_18627125',
 'user_18627820',
 'user_18720675',
 'user_18756584',
 'user_18769488',
 'user_18772411',
 'user_18775584',
 'user_18808550',
 'user_18861304',
 'user_18936033',
 'user_18937306',
 'user_18940083',
 'user_18975290',
 'user_19063208',
 'user_19120854',
 'user_19161047',
 'user_19255622',
 'user_19383682',
 'user_19483237',
 'user_19495488',
 'user_19496841',
 'user_19548301',
 'user_19559172',
 'user_19589889',
 'user_19670031',
 'user_19698926',
 'user_19705979',
 'user_19712266',
 'user_19719474',
 'user_1972994',
 'user_19751605',
 'user_19758669',
 'user_19763465',
 'user_19811127',
 'user_19843719',
 'user_19849324',
 'user_19902470',
 'user_19914319',
 'user_19974750',
 'user_20073587',
 'user_20102441',
 'user_20132528',
 'user_20178850',
 'user_20221884',
 'user_2022901',
 'user_20282137',
 'user_20294047',
 'user_20483194',
 'user_20524760',
 'user_20544314',
 'user_20589508',
 'user_20646247',
 'user_20678957',
 'user_20744643',
 'user_20754234',
 'user_20781071',
 'user_20931287',
 'user_20957066',
 'user_21002854',
 'user_21098031',
 'user_21158843',
 'user_21159981',
 'user_21253572',
 'user_21279850',
 'user_21409408',
 'user_2154724',
 'user_21614523',
 'user_21636790',
 'user_216428',
 'user_21799592',
 'user_21819387',
 'user_2192941',
 'user_21994710',
 'user_22016629',
 'user_22060715',
 'user_22091848',
 'user_22091881',
 'user_22095281',
 'user_22123202',
 'user_22128053',
 'user_22224246',
 'user_22334324',
 'user_22399876',
 'user_22425748',
 'user_22490984',
 'user_22594099',
 'user_22675701',
 'user_22820596',
 'user_22938081',
 'user_22959094',
 'user_22959617',
 'user_23036913',
 'user_23042299',
 'user_23294045',
 'user_23300831',
 'user_23301332',
 'user_23334087',
 'user_23364347',
 'user_2340760',
 'user_23410303',
 'user_23419433',
 'user_23455216',
 'user_23560064',
 'user_23594889',
 'user_23606344',
 'user_23659387',
 'user_2368049',
 'user_23716235',
 'user_23802220',
 'user_23816495',
 'user_23819559',
 'user_23864255',
 'user_23878835',
 'user_23883469',
 'user_2393405',
 'user_23934895',
 'user_23999086',
 'user_2403177',
 'user_24046236',
 'user_24058075',
 'user_24095847',
 'user_24106867',
 'user_24223633',
 'user_24343163',
 'user_24361527',
 'user_24388334',
 'user_24420771',
 'user_24435649',
 'user_24454566',
 'user_24538913',
 'user_24632376',
 'user_24712377',
 'user_24721124',
 'user_24756698',
 'user_24774109',
 'user_24782025',
 'user_24804538',
 'user_24893534',
 'user_24898851',
 'user_24914894',
 'user_24934751',
 'user_2497582',
 'user_24977813',
 'user_24980922',
 'user_25033491',
 'user_25165011',
 'user_25182800',
 'user_25204742',
 'user_25263255',
 'user_25278531',
 'user_25284053',
 'user_25348107',
 'user_25362342',
 'user_25369412',
 'user_25452887',
 'user_25465111',
 'user_25579998',
 'user_25633451',
 'user_25648315',
 'user_25653801',
 'user_2566541',
 'user_25679207',
 'user_25679448',
 'user_25683169',
 'user_25705654',
 'user_25719353',
 'user_25756733',
 'user_25761283',
 'user_25798992',
 'user_25823255',
 'user_25878268',
 'user_25890863',
 'user_25970675',
 'user_2615149',
 'user_26219807',
 'user_26277662',
 'user_26281632',
 'user_26301757',
 'user_2635554',
 'user_26416534',
 'user_26483314',
 'user_26568027',
 'user_26623',
 'user_26683831',
 'user_26692441',
 'user_26729857',
 'user_26743929',
 'user_26746076',
 'user_26792996',
 'user_26821216',
 'user_26898330',
 'user_26931953',
 'user_2699466',
 'user_27013422',
 'user_27032150',
 'user_27050777',
 'user_27081789',
 'user_27096029',
 'user_27171272',
 'user_27281010',
 'user_27294118',
 'user_27299314',
 'user_27371945',
 'user_27392752',
 'user_27532056',
 'user_27633525',
 'user_27677167',
 'user_27841439',
 'user_27844167',
 'user_27844462',
 'user_27934764',
 'user_27945985',
 'user_28080360',
 'user_281210',
 'user_28176494',
 'user_28178169',
 'user_28237458',
 'user_28239172',
 'user_28413361',
 'user_28471281',
 'user_28528877',
 'user_28546926',
 'user_28600038',
 'user_28603655',
 'user_28610284',
 'user_28635315',
 'user_28653904',
 'user_28889766',
 'user_2890558',
 'user_29058506',
 'user_29105814',
 'user_2919633',
 'user_2948332',
 'user_2956844',
 'user_2969399',
 'user_303222',
 'user_3096895',
 'user_3149859',
 'user_3151450',
 'user_3153804',
 'user_3158297',
 'user_3174547',
 'user_3261964',
 'user_3265424',
 'user_328603',
 'user_3410270',
 'user_3465645',
 'user_3546796',
 'user_3586003',
 'user_3611937',
 'user_3612543',
 'user_3613087',
 'user_3614969',
 'user_3646011',
 'user_3700723',
 'user_3750567',
 'user_3845137',
 'user_3912848',
 'user_3997298',
 'user_4039966',
 'user_4049361',
 'user_4063380',
 'user_4101159',
 'user_4120708',
 'user_416810',
 'user_4177863',
 'user_4180377',
 'user_4181231',
 'user_4200480',
 'user_421169',
 'user_4276433',
 'user_4286380',
 'user_4373843',
 'user_4392080',
 'user_441793',
 'user_449923',
 'user_4539093',
 'user_4587389',
 'user_4613364',
 'user_4712861',
 'user_4773492',
 'user_4781692',
 'user_4784431',
 'user_4794584',
 'user_480636',
 'user_4812804',
 'user_4882457',
 'user_4893121',
 'user_5039586',
 'user_5090379',
 'user_5115398',
 'user_513269',
 'user_5271332',
 'user_5309953',
 'user_53391',
 'user_5346501',
 'user_5354169',
 'user_538118',
 'user_5423330',
 'user_5468099',
 'user_549663',
 'user_5593376',
 'user_5612608',
 'user_5643325',
 'user_5677999',
 'user_5692065',
 'user_5693314',
 'user_570607',
 'user_5799666',
 'user_5805724',
 'user_5857758',
 'user_5956532',
 'user_5964667',
 'user_6006796',
 'user_6072689',
 'user_6122237',
 'user_6206368',
 'user_6245016',
 'user_6246001',
 'user_6282227',
 'user_6293411',
 'user_6301425',
 'user_6311103',
 'user_6328144',
 'user_642358',
 'user_6491948',
 'user_6570970',
 'user_6585131',
 'user_659055',
 'user_6752913',
 'user_6768419',
 'user_6786836',
 'user_6820289',
 'user_6928760',
 'user_7032436',
 'user_7084278',
 'user_7102968',
 'user_7251407',
 'user_7283904',
 'user_7391108',
 'user_7528168',
 'user_7564114',
 'user_7746683',
 'user_7758431',
 'user_783973',
 'user_7904799',
 'user_7971982',
 'user_7973778',
 'user_7988523',
 'user_808890',
 'user_8164535',
 'user_819034',
 'user_8290505',
 'user_8334343',
 'user_8428939',
 'user_8462795',
 'user_8539613',
 'user_8555024',
 'user_8576744',
 'user_8614298',
 'user_8653159',
 'user_8685386',
 'user_8742104',
 'user_8800902',
 'user_8803053',
 'user_8846267',
 'user_8867348',
 'user_8925381',
 'user_8957756',
 'user_9019266',
 'user_9053374',
 'user_9065887',
 'user_91442',
 'user_9221378',
 'user_9231076',
 'user_925206',
 'user_9260384',
 'user_9302620',
 'user_9302769',
 'user_93222',
 'user_9615678',
 'user_9644039',
 'user_9717486',
 'user_9933393',
 'user_9940903'}

In [74]:
df_20_aug = df2.copy(deep=True)

In [145]:
df_21_aug[df_21_aug['video_title'].apply(lambda x: x.startswith('Красная смородина'))]['author_title']

2600               Костя и Ксюша Абрамович
703688    ЛЮБОЗНАТЕЛЬНЫЙ ! СВОИМИ РУКАМИ !
959720             Костя и Ксюша Абрамович
Name: author_title, dtype: object

In [137]:
df_20_aug[df_20_aug['user_id'] == 'user_10905320']['video_title']

67217                               Лучшая карточная смена
67218    Подарок от отца - отдых в загородном клубе | Д...
67219                                 Поездка в Краснодар.
67220        ❤️ Распаковка РОБОТА VAN с персонажами BT21❤️
67221    Как сделать идеальный молочный коктейль? ?Откр...
67222    ❤️ Лепим ПЕЧЕНЬКИ С ПРЕДСКАЗАНИЯМИ из полимерн...
Name: video_title, dtype: object

In [138]:
df_21_aug[df_21_aug['user_id'] == 'user_10905320']['video_title']

69176    Распаковка новых стикеров
69177        Черно-Белый Флюид Арт
Name: video_title, dtype: object

In [136]:
df_21_aug[df_21_aug['user_id'] == 'user_10347108']

,Unnamed: 0,user_id,item_id,date_watch,watch_time,is_autorized,date_reaction,pos_emo,is_v_top,neg_emo,...,video_description,category_title,publicated,duration,channel_sub,tv_sub,ctr.CTR_10days_21_07,ctr.CTR_10days_01_08,ctr.CTR_10days_10_08,ctr.CTR_10days_21_08
27170,27170,user_10347108,video_1001019,2023-08-21 09:25:58+03:00,31,1,NaN,NaN,NaN,NaN,...,NaN,Здоровье,2023-08-21 09:21:10+03:00,60.001,15,0,0.0,0.0,0.0,0.500000
27171,27171,user_10347108,video_1003500,2023-08-21 14:11:02+03:00,11,1,NaN,NaN,NaN,NaN,...,Винтажная версия клипа: https://clck.ru/35NW64...,Музыка,2023-08-21 14:08:22+03:00,270.471,69,0,0.0,0.0,0.0,0.000000
27172,27172,user_10347108,video_1011905,2023-08-21 10:41:16+03:00,21,1,NaN,NaN,NaN,NaN,...,Иногда всё так сложно... просо обхохочешьсся.....,Развлечения,2023-08-23 12:30:08+03:00,60.502,448,0,0.0,0.0,0.0,0.000000
27173,27173,user_10347108,video_101413,2023-08-21 11:40:33+03:00,31,1,NaN,NaN,NaN,NaN,...,NaN,Разное,2023-08-21 11:40:23+03:00,50.132,3,0,0.0,0.0,0.0,0.000000
27174,27174,user_10347108,video_1017538,2023-08-21 15:23:18+03:00,11,1,NaN,NaN,NaN,NaN,...,уборка на столе,Развлечения,2023-08-21 15:18:23+03:00,21.300,1,0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27605,27605,user_10347108,video_975656,2023-08-21 13:33:03+03:00,21,1,NaN,NaN,NaN,NaN,...,NaN,Бизнес и предпринимательство,2023-08-21 13:21:16+03:00,1916.880,0,0,0.0,0.0,0.0,0.000000
27606,27606,user_10347108,video_979466,2023-08-21 12:36:41+03:00,11,1,NaN,NaN,NaN,NaN,...,"Дорогие мои, с огромным удовольствием представ...",Красота,2023-08-21 19:00:14+03:00,36.036,1,0,0.0,0.0,0.0,0.000000
27607,27607,user_10347108,video_980791,2023-08-21 14:36:14+03:00,11,1,NaN,NaN,NaN,NaN,...,#fnaf #floppa #fivenightsatFloppa2,Видеоигры,2023-08-21 17:28:47+03:00,390.913,10,0,0.0,0.0,0.0,0.000000
27608,27608,user_10347108,video_992869,2023-08-21 10:06:41+03:00,123,1,NaN,NaN,NaN,NaN,...,Покупка игр через Турцию: https://19bit.ru (Не...,Видеоигры,2023-08-21 10:07:30+03:00,781.206,29,0,0.0,0.0,0.0,0.045455
27609,27609,user_10347108,video_994856,2023-08-21 14:49:31+03:00,1,1,NaN,NaN,NaN,NaN,...,Урок 65. Конус\nАвтор: Матафонова Зинаида Анат...,Образование,2023-08-21 14:49:12+03:00,79.018,282,0,0.0,0.0,0.0,0.000000

In [135]:
df_21_aug.groupby('user_id').agg({'category_title': lambda x: len(x.unique())}).reset_index().sort_values(by='category_title',ascending=False)

               user_id  category_title
987478    user_3488372              39
434661   user_18680065              37
319728   user_16377023              37
1251675    user_876011              37
17579    user_10347108              37
...                ...             ...
453700   user_19064091               1
453699   user_19064080               1
453698   user_19064063               1
453697   user_19064015               1
1313878   user_9999986               1

[1313879 rows x 2 columns]

In [146]:
hack = df2.copy(deep=True)

In [147]:
hack['pos_emo'].unique()

array([nan, 'Like', 'Heart', 'New_Fire', '', 'Laugh',
       'Happy_Star_glasses', 'Happy_glasses'], dtype=object)

In [148]:
# top = 1.3 - есть реакция, 1 - нет реакции
# pos = 1.2 - есть реакция, 1 - нет реакции
hack['new_is_v_top'] = np.where(hack['is_v_top'] == 1, 1.3, 1)
hack['new_pos_emo'] = np.where(hack['pos_emo'].isna(), 1, 1.2)
hack = hack.drop(columns={'is_v_top', 'pos_emo'})
hack = hack.rename(columns={'new_is_v_top':'is_v_top', 'new_pos_emo':'pos_emo'})

In [1]:
hack['pos_emo'].unique()

NameError: name 'hack' is not defined

In [153]:
len(hack['item_id'].unique())

261269