In [1]:
import pandas as pd
import numpy as np

In [2]:
df_stats = pd.read_csv("small_player_starts_train.csv")
df_emotions = pd.read_csv("emotions.csv")

In [3]:
df_stats.head()

,date,user_id,item_id,watch_time,is_autorized
0,2023-08-21 15:53:30+03:00,user_7941459,video_1535803,22,0
1,2023-08-21 16:17:58+03:00,user_17893165,video_796847,374,0
2,2023-08-21 21:18:12+03:00,user_25219604,video_1905049,11,0
3,2023-08-21 01:06:10+03:00,user_24477183,video_1156618,1,0
4,2023-08-21 17:24:32+03:00,user_25483180,video_500499,20,0

In [4]:
# Фильтр реакций по 21.08.2023
df_emotions = df_emotions[(df_emotions['date'] >= '2023-08-21') & (df_emotions['date'] < '2023-08-22')]

In [5]:
df_emotions[df_emotions.duplicated(subset=['user_id', 'item_id'],keep=False)].sort_values(by=['user_id','item_id'])

,date,user_id,item_id,type,emoji
86343,2023-08-21 17:22:11+03:00,user_10012865,video_2177347,v_top,v_top
109499,2023-08-21 17:22:10+03:00,user_10012865,video_2177347,pos_emotions,Heart
97709,2023-08-21 13:50:07+03:00,user_10012865,video_320208,v_top,v_top
308864,2023-08-21 13:50:13+03:00,user_10012865,video_320208,pos_emotions,Like
10212,2023-08-21 00:09:34+03:00,user_10021075,video_2138244,v_top,v_top
...,...,...,...,...,...
308853,2023-08-21 14:31:37+03:00,user_9942135,video_320208,pos_emotions,New_Fire
94074,2023-08-21 06:07:26+03:00,user_9949652,video_839839,pos_emotions,Like
101253,2023-08-21 06:07:32+03:00,user_9949652,video_839839,v_top,v_top
108002,2023-08-21 20:53:36+03:00,user_9988260,video_940974,v_top,v_top
368512,2023-08-21 20:53:43+03:00,user_9988260,video_940974,pos_emotions,Happy_glasses

In [6]:
#pd.merge(df_stats, df_emotions,how='left', )

In [7]:
df_new_emo = df_emotions.copy(deep=True)

In [8]:
df_new_emo['type'].unique()

array(['v_top', 'pos_emotions', 'neg_emotions'], dtype=object)

In [9]:
df_new_emo

,date,user_id,item_id,type,emoji
73,2023-08-21 09:41:37+03:00,user_2142397,video_125790,v_top,v_top
79,2023-08-21 01:52:16+03:00,user_718921,video_125790,v_top,v_top
80,2023-08-21 10:59:20+03:00,user_21944136,video_125790,v_top,v_top
81,2023-08-21 12:50:33+03:00,user_24338405,video_125790,v_top,v_top
84,2023-08-21 16:19:43+03:00,user_26889771,video_125790,v_top,v_top
...,...,...,...,...,...
369106,2023-08-21 12:16:30+03:00,user_9694861,video_1739074,pos_emotions,Like
369137,2023-08-21 05:24:50+03:00,user_28179811,video_706182,pos_emotions,Like
369179,2023-08-21 07:05:23+03:00,user_11644428,video_706182,pos_emotions,Like
369218,2023-08-21 00:20:37+03:00,user_4565406,video_863664,pos_emotions,Like
369349,2023-08-21 08:11:12+03:00,user_7592585,video_1172738,pos_emotions,Like

In [10]:
df_new_emo['is_v_top'] = np.where(df_new_emo['type'] == 'v_top', 1, 0)
df_new_emo['pos_emo'] = np.where(df_new_emo['type'] == 'pos_emotions', df_new_emo['emoji'], '')
df_new_emo['neg_emo'] = np.where(df_new_emo['type'] == 'neg_emotions', df_new_emo['emoji'], '')

In [11]:
df_new_emo[df_new_emo.duplicated(subset=['user_id','item_id'],keep=False)].sort_values(by=['user_id','item_id'])

,date,user_id,item_id,type,emoji,is_v_top,pos_emo,neg_emo
86343,2023-08-21 17:22:11+03:00,user_10012865,video_2177347,v_top,v_top,1,,
109499,2023-08-21 17:22:10+03:00,user_10012865,video_2177347,pos_emotions,Heart,0,Heart,
97709,2023-08-21 13:50:07+03:00,user_10012865,video_320208,v_top,v_top,1,,
308864,2023-08-21 13:50:13+03:00,user_10012865,video_320208,pos_emotions,Like,0,Like,
10212,2023-08-21 00:09:34+03:00,user_10021075,video_2138244,v_top,v_top,1,,
...,...,...,...,...,...,...,...,...
308853,2023-08-21 14:31:37+03:00,user_9942135,video_320208,pos_emotions,New_Fire,0,New_Fire,
94074,2023-08-21 06:07:26+03:00,user_9949652,video_839839,pos_emotions,Like,0,Like,
101253,2023-08-21 06:07:32+03:00,user_9949652,video_839839,v_top,v_top,1,,
108002,2023-08-21 20:53:36+03:00,user_9988260,video_940974,v_top,v_top,1,,
368512,2023-08-21 20:53:43+03:00,user_9988260,video_940974,pos_emotions,Happy_glasses,0,Happy_glasses,

In [12]:
df_new_emo.agg({'pos_emo': 'sum', 'is_v_top':'sum', 'neg_emo': 'sum'})

pos_emo     LikeLikeLikeLikeLikeHappy_Star_glassesLikeLike...
is_v_top                                                 6481
neg_emo     SicknessDislikeAngryDislikeDislikeAngryDislike...
dtype: object

In [14]:
df_new_emo = df_new_emo.groupby(by=['user_id', 'item_id']).agg({'date': 'min','pos_emo': 'sum', 'is_v_top':'sum', 'neg_emo': 'sum'}).reset_index()

In [61]:
df_stats_grouped = df_stats.groupby(by=['user_id','item_id']).agg({'date': 'min', 'watch_time': 'sum', 'is_autorized':'sum'})

In [62]:
df_stats_grouped = df_stats_grouped.reset_index()

In [63]:
df_stats_grouped = df_stats_grouped[df_stats_grouped['is_autorized'] < 15]

In [64]:
df_stats_grouped.loc[df_stats_grouped.is_autorized > 0, 'is_autorized'] = 1

In [65]:
df2 = pd.merge(left=df_stats_grouped,right=df_new_emo,how='left',on=['user_id','item_id'])

In [66]:
df2 = df2.rename(columns={'date_x': 'date_watch', 'date_y': 'date_reaction'})

In [69]:
df_meta_video = pd.read_parquet('videos.parquet')

ArrowMemoryError: realloc of size 1056964608 failed

In [72]:
df2 = pd.merge(left=df2,right=df_meta_video, how='left', on='item_id')

In [76]:
df2['duration'] = df2['duration']/1000
df2['ctr.CTR_10days_21_07'] = df2['ctr.CTR_10days_21_07'].fillna(0)
df2['ctr.CTR_10days_01_08'] = df2['ctr.CTR_10days_01_08'].fillna(0)
df2['ctr.CTR_10days_10_08'] = df2['ctr.CTR_10days_10_08'].fillna(0)
df2['ctr.CTR_10days_21_08'] = df2['ctr.CTR_10days_21_08'].fillna(0)

In [78]:
df2.to_csv('user_video_reaction_meta.csv')